spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/crm_database
spring.datasource.username=crm_user
spring.datasource.password=crm_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true